### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by ramontayag** [pixels-and-bits/jabe#2]
I wanted to upgrade `simple_form` but I'm unable to run tests. I first added the `database.yml`, then I ran `rake test` from the root of jabe (not the dummy Rails app). The error I got:

```
** Invoke load_app (first_time)
** Execute load_app
** Invoke test (first_time)
** Execute test
/Users/ramon/src/jabe/config/initializers/devise.rb:1:in `<top (required)>': uninitialized constant Devise (NameError)
        from /Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.2.0/lib/rails/engine.rb:588:in `block (2 levels) in <class:Engine>'
        from /Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.2.0/lib/rails/engine.rb:587:in `each'
        from /Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.2.0/lib/rails/engine.rb:587:in `block in <class:Engine>'
        from /Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.2.0/lib/rails/initializable.rb:30:in `instance_exec'
        from /Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.2.0/lib/rails/initializable.rb:30:in `run'
        from /Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.2.0/lib/rails/initializable.rb:54:in `each'
        from /Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.2.0/lib/rails/initializable.rb:54:in `run_initializers'
        from /Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.2.0/lib/rails/application.rb:136:in `initialize!'
        from /Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.2.0/lib/rails/railtie/configurable.rb:30:in `method_missing'
        from /Users/ramon/src/jabe/test/dummy/config/environment.rb:5:in `<top (required)>'
        from /Users/ramon/src/jabe/test/test_helper.rb:4:in `require'
        from /Users/ramon/src/jabe/test/test_helper.rb:4:in `<top (required)>'
        from /Users/ramon/src/jabe/test/integration/navigation_test.rb:1:in `require'
        from /Users/ramon/src/jabe/test/integration/navigation_test.rb:1:in `<top (required)>'
        from /Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:10:in `require'
        from /Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
        from /Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:9:in `each'
        from /Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:9:in `block in <main>'
        from /Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:4:in `select'
        from /Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [/Users/ramon/.rvm/rubies/ruby-1.9.2-p290/b...]
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/file_utils.rb:53:in `block in create_shell_runner'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/file_utils.rb:45:in `call'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/file_utils.rb:45:in `sh'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/file_utils_ext.rb:39:in `sh'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/file_utils.rb:82:in `ruby'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/file_utils_ext.rb:39:in `ruby'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/testtask.rb:99:in `block (2 levels) in define'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/file_utils_ext.rb:60:in `verbose'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/testtask.rb:98:in `block in define'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/ramon/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/bin/rake:19:in `load'
/Users/ramon/.rvm/gems/ruby-1.9.2-p290/bin/rake:19:in `<main>'
Tasks: TOP => test
```

**Comment by UnderpantsGnome** [comment]
I don't think the tests are hooked up in current versions of JABE. I can't think of anything offhand that would cause issues with a simple_form upgrade. The bootstrap branch is using 2.0.0rc. This project hasn't gotten much attention lately, that might change in the not too distant future.

**Comment by ramontayag** [comment]
Ok I missed this comment. Since it's not relevant I'll close it then. :) Thanks!
